# -*- coding: utf-8 -*-
"""Prerequisite review content. Rendered by build_site.py into prereq/ pages so students
can self-assess and refresh the math, Python, and ML background the course assumes."""

PREREQ = {
    "math": {
        "title": "Mathematics",
        "icon": "&#8721;",
        "intro": "Deep learning is applied linear algebra and calculus with a probabilistic flavor. "
                 "A mathematician's depth is not required, but these ideas should feel familiar so the "
                 "course can move quickly from notation to networks.",
        "sections": [
            {"h": "Linear algebra", "points": [
                "Vectors and matrices: ordered lists and grids of numbers, and how to add and scale them.",
                "Matrix multiplication and the dot product, and which shapes are compatible (the inner dimensions must match).",
                "Vector norms (L1 sums absolute values, L2 is Euclidean length) and the dot product as a measure of angle and projection.",
                "Rank as the number of independent directions in a matrix, with a light acquaintance with eigenvalues and the SVD.",
            ]},
            {"h": "Probability and statistics", "points": [
                "Random variables and distributions: how outcomes are spread over possible values, discrete or continuous.",
                "Expectation (the long-run average), variance, and standard deviation (how far values spread from the mean).",
                "Conditional probability (the chance of one event given another), independence, and Bayes' rule.",
                "Likelihood: how probable observed data is under a model, and why logarithms make it convenient to work with.",
            ]},
            {"h": "Multivariable functions", "points": [
                "Functions of several variables and the surfaces they trace out.",
                "Partial derivatives (the slope in one variable while the others are held fixed) and the gradient (the vector of all of them).",
                "The chain rule for differentiating a function of a function (a composition).",
                "A light feel for the Jacobian (first derivatives of several outputs) and the Hessian (second derivatives).",
            ]},
            {"h": "Gradients and optimization", "points": [
                "The gradient points in the direction in which a function increases fastest.",
                "Gradient descent: repeatedly step in the opposite (downhill) direction to reach a minimum.",
                "Step-size (learning-rate) intuition: too large overshoots and diverges, too small is very slow.",
                "Local versus global minima, and why convex functions are easy to minimize (every local minimum is global).",
            ]},
        ],
        "checklist": [
            "Multiply two matrices by hand and state the result shape.",
            "Compute a gradient of a simple multivariable function.",
            "Explain what expectation and variance measure.",
            "Describe how gradient descent uses the gradient.",
        ],
        "mcq": [
            {"q": "If A is 3x4 and B is 4x2, the product AB has shape:", "options": ["4x4", "3x2", "2x3", "undefined"], "answer": 1,
             "why": "The inner dimensions (4) match, and the result takes the outer dimensions: 3x2."},
            {"q": "Matrix multiplication is:", "options": ["commutative (AB = BA)", "generally not commutative", "only defined for square matrices", "the same as the elementwise product"], "answer": 1,
             "why": "In general AB does not equal BA; order matters, and the elementwise (Hadamard) product is a different operation."},
            {"q": "The transpose of a product (AB) equals:", "options": ["A B transposed each", "B-transpose times A-transpose", "AB", "BA"], "answer": 1,
             "why": "Transposing a product reverses the order: (AB)^T = B^T A^T."},
            {"q": "The dot product of two non-zero vectors is zero when they are:", "options": ["parallel", "of unit length", "orthogonal (perpendicular)", "equal"], "answer": 2,
             "why": "u . v = |u||v|cos(theta); it is zero when the angle is 90 degrees."},
            {"q": "The L2 (Euclidean) norm of the vector (3, 4) is:", "options": ["7", "5", "12", "25"], "answer": 1,
             "why": "sqrt(3^2 + 4^2) = sqrt(25) = 5."},
            {"q": "For a fair six-sided die, the expected value of one roll is:", "options": ["3", "3.5", "6", "1"], "answer": 1,
             "why": "(1+2+3+4+5+6)/6 = 21/6 = 3.5."},
            {"q": "Variance measures:", "options": ["the average value", "the most frequent value", "the spread around the mean", "the maximum value"], "answer": 2,
             "why": "Variance is the expected squared deviation from the mean."},
            {"q": "Two events A and B are independent when:", "options": ["P(A and B) = P(A) + P(B)", "P(A and B) = P(A) P(B)", "they are mutually exclusive", "P(A given B) = 0"], "answer": 1,
             "why": "Independence means the joint probability factorizes into the product of the marginals."},
            {"q": "Bayes' rule writes P(A given B) in terms of:", "options": ["P(B given A), P(A), P(B)", "P(A) + P(B)", "P(A) P(B) only", "P(A - B)"], "answer": 0,
             "why": "P(A|B) = P(B|A) P(A) / P(B)."},
            {"q": "The partial derivative of f(x, y) = x^2 y with respect to x treats:", "options": ["both x and y as variables", "y as a constant", "x as a constant", "f as constant"], "answer": 1,
             "why": "A partial derivative w.r.t. x holds the other variables (y) constant, giving 2xy."},
            {"q": "The gradient of a scalar function points in the direction of:", "options": ["steepest descent", "zero change", "steepest ascent", "the x-axis"], "answer": 2,
             "why": "The gradient points toward the greatest rate of increase; its negative is the steepest-descent direction."},
            {"q": "The chain rule gives the derivative of f(g(x)) as:", "options": ["f'(x) g'(x)", "f'(g(x)) times g'(x)", "f'(g(x))", "g'(f(x))"], "answer": 1,
             "why": "Differentiate the outer function at the inner value, times the derivative of the inner function."},
            {"q": "To minimize a function, gradient descent moves a parameter:", "options": ["along the gradient", "opposite the gradient", "perpendicular to the gradient", "randomly"], "answer": 1,
             "why": "It steps in the negative-gradient direction, scaled by the learning rate."},
            {"q": "If the learning rate is far too large, gradient descent typically:", "options": ["converges faster with no downside", "diverges or oscillates", "stops immediately", "ignores the gradient"], "answer": 1,
             "why": "Overshooting the minimum makes the loss oscillate or blow up."},
            {"q": "A function is convex if:", "options": ["it has many local minima", "any local minimum is also global", "its gradient is always zero", "it is always increasing"], "answer": 1,
             "why": "For convex functions every local minimum is global, which makes optimization reliable."},
        ],
        "resources": [
            {"title": "3Blue1Brown: Essence of Linear Algebra", "url": "https://www.3blue1brown.com/topics/linear-algebra"},
            {"title": "3Blue1Brown: Essence of Calculus", "url": "https://www.3blue1brown.com/topics/calculus"},
            {"title": "Khan Academy: Multivariable Calculus", "url": "https://www.khanacademy.org/math/multivariable-calculus"},
            {"title": "Mathematics for Machine Learning (free book)", "url": "https://mml-book.github.io/"},
        ],
    },
    "python": {
        "title": "Python Foundations & Advanced Features",
        "icon": "&#128013;",
        "intro": "PyTorch is a Python library, and idiomatic Python makes deep-learning code short and "
                 "readable. Beyond the basics, a handful of features appear constantly in PyTorch and "
                 "data code; know them and the framework stops feeling mysterious.",
        "sections": [
            {"h": "Core Python", "points": [
                "Data types (numbers, strings, lists, dicts), control flow (if, for, while), functions, and modules.",
                "Classes and objects: bundling related data and behavior together (the basis of most libraries).",
                "Slicing and negative indexing to read parts of a sequence.",
            ]},
            {"h": "Idiomatic and advanced features", "points": [
                "List, dict, and set comprehensions: build a collection in one readable expression.",
                "Generators and iterators (the yield keyword): produce values lazily, one at a time.",
                "lambda (small anonymous functions) and *args / **kwargs (flexible argument lists).",
                "enumerate (index with item), zip (pair up iterables), f-strings, and context managers (the with statement).",
                "Decorators at a reading level: a function that wraps another to change its behavior.",
            ]},
            {"h": "Useful dunder (magic) methods", "points": [
                "__init__: the constructor that sets up a new object.",
                "__len__ and __getitem__: make an object respond to len(obj) and obj[i].",
                "__call__: make an instance callable like a function, so obj(x) runs the object's logic.",
                "__repr__: a readable text representation of an object, useful for debugging.",
            ]},
            {"h": "NumPy versus Python lists", "points": [
                "An ndarray stores one numeric type in contiguous memory; a Python list holds arbitrary objects and is slower.",
                "Vectorized operations apply to a whole array at once, replacing explicit element-by-element loops.",
                "Broadcasting (combining different but compatible shapes) and dtypes (the element type).",
                "Converting between arrays and tensors with simple helper functions.",
            ]},
            {"h": "What recurs in PyTorch and DL code", "points": [
                "Fancy indexing and boolean masks to select elements by position or by a condition.",
                "Broadcasting to combine arrays of different shapes without writing loops.",
                "In-place operations (methods ending in an underscore) that modify data directly.",
                "Moving data between the CPU and the GPU.",
            ]},
        ],
        "checklist": [
            "Rewrite a for-loop that builds a list as a comprehension.",
            "Write a generator that yields batches from a list.",
            "Implement a tiny class with __len__ and __getitem__.",
            "Explain why a NumPy vectorized op beats a Python loop.",
        ],
        "mcq": [
            {"q": "The list comprehension [x*x for x in range(4)] produces:", "options": ["[0, 1, 2, 3]", "[1, 4, 9, 16]", "[0, 1, 4, 9]", "[0, 2, 4, 6]"], "answer": 2,
             "why": "range(4) is 0,1,2,3; their squares are 0,1,4,9."},
            {"q": "A generator function is one that uses:", "options": ["return", "yield", "lambda", "async"], "answer": 1,
             "why": "yield turns a function into a generator that produces values lazily, one at a time."},
            {"q": "The main advantage of a generator over a list is:", "options": ["faster indexing", "lazy, memory-efficient iteration", "automatic sorting", "built-in JSON support"], "answer": 1,
             "why": "A generator produces items on demand without holding the whole sequence in memory."},
            {"q": "Which dunder methods let an object support len(obj) and obj[i]?", "options": ["__init__ and __str__", "__len__ and __getitem__", "__call__ and __repr__", "__add__ and __eq__"], "answer": 1,
             "why": "__len__ backs len(); __getitem__ backs indexing and iteration (exactly what a Dataset implements)."},
            {"q": "Defining __call__ on a class allows:", "options": ["printing the object", "calling the instance like a function: obj(x)", "adding two objects", "iterating it"], "answer": 1,
             "why": "__call__ makes instances callable; e.g. model(x) runs the object's logic."},
            {"q": "zip([1, 2, 3], ['a', 'b', 'c']) yields:", "options": ["(1, 2, 3, 'a', 'b', 'c')", "(1, 'a'), (2, 'b'), (3, 'c')", "a dictionary", "[1, 'a', 2, 'b']"], "answer": 1,
             "why": "zip pairs elements positionally from the iterables."},
            {"q": "enumerate(['a', 'b']) yields:", "options": ["'a', 'b'", "(0, 'a'), (1, 'b')", "(1, 'a'), (2, 'b')", "['a', 'b']"], "answer": 1,
             "why": "enumerate pairs each item with its index, starting at 0 by default."},
            {"q": "In def f(*args, **kwargs), kwargs is:", "options": ["a list of positional args", "a dict of keyword args", "a single value", "the return value"], "answer": 1,
             "why": "*args collects extra positional arguments as a tuple; **kwargs collects keyword arguments as a dict."},
            {"q": "The slice a[1:4] returns the elements at indices:", "options": ["1, 2, 3, 4", "1, 2, 3", "0, 1, 2, 3", "2, 3, 4"], "answer": 1,
             "why": "Slicing is start-inclusive and stop-exclusive: indices 1, 2, 3."},
            {"q": "a[-1] refers to:", "options": ["an error", "the first element", "the last element", "index minus one, which is skipped"], "answer": 2,
             "why": "Negative indices count from the end; -1 is the last element."},
            {"q": "The main reason a NumPy array is faster than a Python list for numeric work:", "options": ["it uses more memory", "typed, contiguous storage with vectorized operations", "it is written in Java", "it caches results"], "answer": 1,
             "why": "Homogeneous typed memory and vectorized C-level operations avoid slow per-element Python loops."},
            {"q": "NumPy broadcasting aligns array shapes starting from:", "options": ["the leading (first) dimension", "the trailing (last) dimension", "the largest dimension", "alphabetical order"], "answer": 1,
             "why": "Shapes are compared from the trailing axis; sizes must be equal or one of them 1."},
            {"q": "A Python list is ____ and a tuple is ____:", "options": ["immutable; mutable", "mutable; immutable", "both mutable", "both immutable"], "answer": 1,
             "why": "Lists can be modified in place; tuples cannot."},
            {"q": "The expression {k: v for k, v in pairs} is a:", "options": ["set comprehension", "generator", "dict comprehension", "lambda"], "answer": 2,
             "why": "The {key: value for ...} form builds a dictionary."},
            {"q": "A lambda in Python is:", "options": ["a class", "a small anonymous function", "a loop", "a module"], "answer": 1,
             "why": "lambda defines a short, unnamed function, e.g. lambda x: x + 1."},
        ],
        "resources": [
            {"title": "The Python Tutorial (official)", "url": "https://docs.python.org/3/tutorial/"},
            {"title": "Real Python: List Comprehensions", "url": "https://realpython.com/list-comprehension-python/"},
            {"title": "Real Python: Generators", "url": "https://realpython.com/introduction-to-python-generators/"},
            {"title": "NumPy: the absolute basics for beginners", "url": "https://numpy.org/doc/stable/user/absolute_beginners.html"},
        ],
    },
    "ml": {
        "title": "Basic Machine Learning Concepts",
        "icon": "&#129518;",
        "intro": "This course assumes an introductory machine-learning course. Deep learning reuses its "
                 "vocabulary, models, losses, splits, and the overfitting story, so the network material "
                 "lands on familiar ground.",
        "sections": [
            {"h": "Supervised learning", "points": [
                "Regression predicts a continuous number; classification predicts a category.",
                "Features (inputs), labels (targets), and the train/test split that estimates how well a model generalizes.",
                "Linear and logistic regression as the simplest baseline models.",
            ]},
            {"h": "Error, cost, and loss", "points": [
                "A loss measures the error on one example; the cost (objective) aggregates it over the whole dataset.",
                "Mean squared error for regression; cross-entropy for classification.",
                "The loss is what training minimizes; the metric (such as accuracy) is the number reported to people.",
            ]},
            {"h": "Overfitting and generalization", "points": [
                "Training error (on data already seen) versus test error (on new data), and why the gap matters.",
                "Train, validation, and test splits, and cross-validation for a more stable estimate.",
                "Learning curves and the gap between training and validation performance.",
            ]},
            {"h": "Regularization", "points": [
                "L2 (weight decay) penalizes large weights; L1 also drives some weights to exactly zero (sparsity).",
                "Early stopping (halting before overfitting) and data augmentation.",
                "Regularization trades a little training fit for better generalization.",
            ]},
            {"h": "The bias-variance dilemma", "points": [
                "High bias means underfitting (too simple); high variance means overfitting (too complex).",
                "Model capacity and dataset size move a model between these two failure modes.",
                "The aim is the balance point that minimizes error on new data.",
            ]},
            {"h": "Other essentials", "points": [
                "Gradient descent and the learning rate as the core idea of the training loop.",
                "Feature scaling and normalization so inputs sit on comparable ranges.",
                "Evaluation metrics: accuracy, precision, recall, F1, ROC/AUC, and the confusion matrix.",
                "Parameters (learned) versus hyperparameters (set by hand), baselines, data leakage, and class imbalance.",
            ]},
        ],
        "checklist": [
            "State whether a task is regression or classification and pick a loss.",
            "Explain overfitting using the train/validation gap.",
            "Describe how L2 regularization changes the objective.",
            "Read a confusion matrix and compute precision and recall.",
        ],
        "mcq": [
            {"q": "Predicting a house price (a continuous number) is a:", "options": ["classification task", "regression task", "clustering task", "ranking task"], "answer": 1,
             "why": "Regression predicts continuous values; classification predicts discrete classes."},
            {"q": "A typical loss for binary classification is:", "options": ["mean squared error", "binary cross-entropy", "R-squared", "accuracy"], "answer": 1,
             "why": "Cross-entropy (log loss) matches probabilistic classification; accuracy is a metric, not a loss."},
            {"q": "The difference between a loss and a metric is:", "options": ["they are the same", "the loss is optimized in training; the metric is the reported measure", "the metric is always the loss", "the loss is only for testing"], "answer": 1,
             "why": "Training minimizes the differentiable loss; the metric is the human-facing measure, and the two can differ."},
            {"q": "Overfitting is indicated by:", "options": ["high training error and high test error", "low training error and high test error", "low error on both", "high error on training only"], "answer": 1,
             "why": "The model memorizes the training data (low train error) but generalizes poorly (high test error)."},
            {"q": "The validation set is used to:", "options": ["train the weights", "tune hyperparameters and select models", "report the final result", "increase the data size"], "answer": 1,
             "why": "The validation set guides model and hyperparameter choices; the test set is the untouched final measure."},
            {"q": "k-fold cross-validation:", "options": ["trains once on all data", "splits data into k folds and rotates the validation fold", "only works for images", "removes the need for a test set"], "answer": 1,
             "why": "Each fold serves as validation once; the results are averaged for a more robust estimate."},
            {"q": "L2 regularization (weight decay) penalizes:", "options": ["the sum of absolute weights", "the sum of squared weights", "the number of layers", "the learning rate"], "answer": 1,
             "why": "L2 penalizes squared weight magnitude; L1 penalizes absolute values."},
            {"q": "Compared with L2, L1 regularization tends to produce:", "options": ["denser weights", "sparser weights (more exact zeros)", "larger weights", "no effect"], "answer": 1,
             "why": "The L1 penalty drives some weights exactly to zero, giving sparse solutions."},
            {"q": "The bias-variance trade-off says that:", "options": ["bias and variance are unrelated", "reducing one often increases the other", "both always decrease together", "variance is always zero"], "answer": 1,
             "why": "Simple models have high bias and low variance; complex models the reverse. The goal balances them."},
            {"q": "A model that is too simple for the data has:", "options": ["high variance", "high bias (underfitting)", "perfect accuracy", "too many parameters"], "answer": 1,
             "why": "Underfitting is high bias: the model cannot capture the underlying pattern."},
            {"q": "Why can accuracy be misleading on imbalanced data?", "options": ["it cannot be computed", "a trivial majority-class predictor can score high", "it requires probabilities", "it only works for regression"], "answer": 1,
             "why": "With 95% of one class, always predicting that class scores 95% while missing the minority entirely."},
            {"q": "Precision is defined as:", "options": ["TP / (TP + FN)", "TP / (TP + FP)", "(TP + TN) / all", "FP / all"], "answer": 1,
             "why": "Precision is true positives over predicted positives; recall is TP / (TP + FN)."},
            {"q": "The F1 score is:", "options": ["the sum of precision and recall", "the harmonic mean of precision and recall", "accuracy minus error", "the area under the ROC curve"], "answer": 1,
             "why": "F1 = 2 P R / (P + R), balancing precision and recall in one number."},
            {"q": "A parameter and a hyperparameter differ in that:", "options": ["they are identical", "parameters are learned from data; hyperparameters are set before training", "hyperparameters are learned by backprop", "parameters are chosen by hand"], "answer": 1,
             "why": "Weights are parameters learned in training; learning rate, depth, etc. are hyperparameters set beforehand."},
            {"q": "Data leakage is:", "options": ["losing data files", "information from the test set or future leaking into training", "a memory error", "having too little data"], "answer": 1,
             "why": "For example, scaling with statistics computed over the whole dataset before splitting inflates results."},
        ],
        "resources": [
            {"title": "Google Machine Learning Crash Course", "url": "https://developers.google.com/machine-learning/crash-course"},
            {"title": "An Introduction to Statistical Learning (free book)", "url": "https://www.statlearning.com/"},
            {"title": "StatQuest: Machine Learning playlist", "url": "https://www.youtube.com/playlist?list=PLblh5JKOoLUICTaGLRoHQDuF_7q2GfuJF"},
            {"title": "scikit-learn: Metrics and scoring", "url": "https://scikit-learn.org/stable/modules/model_evaluation.html"},
        ],
    },
}

ORDER = ["math", "python", "ml"]
