# -*- coding: utf-8 -*-
"""Example project briefs for the mid-term mini-project and the final project.
Rendered by build_site.py into projects/ pages."""

PROJECTS = {
    "midterm": {
        "title": "Mid-term mini-project examples",
        "badge": "Mid-term",
        "meta": "20% of the grade · around weeks 9 to 10 · CNN-based",
        "intro": "The mid-term is a convolutional-network project on an image task: build it, train it, "
                 "run a controlled ablation, and report what you found. Pick one of the examples below or "
                 "propose your own in the same spirit. Datasets are suggestions; any comparable small image "
                 "dataset works.",
        "deliverables": [
            "Working, documented code (a notebook or a small repo).",
            "A short report (about 2 pages) with training curves and an ablation table.",
            "A clear statement of what the ablation showed and why.",
        ],
        "fields": [("data", "Data"), ("goal", "Goal"), ("build", "Build"), ("study", "Required study"), ("stretch", "Stretch goal")],
        "examples": [
            {"title": "Residual CNN on CIFAR-10",
             "data": "CIFAR-10.", "goal": "A strong image classifier.",
             "build": "A small ResNet-style CNN with batch normalization and residual blocks.",
             "study": "Ablate batch normalization and residual connections; report accuracy and training curves for each variant.",
             "stretch": "Add mixup or cutout augmentation and measure the gain."},
            {"title": "Depth and width study on FashionMNIST",
             "data": "FashionMNIST.", "goal": "Understand model capacity.",
             "build": "A configurable CNN whose depth and width you can vary.",
             "study": "Sweep depth and width; plot accuracy against parameter count and identify under- and over-fitting.",
             "stretch": "Add dropout and weight decay and compare the curves."},
            {"title": "Small-data classifier with augmentation",
             "data": "Oxford-IIIT Pets or Flowers-102 subset.", "goal": "Classify with limited data.",
             "build": "A CNN trained from scratch.",
             "study": "Data-augmentation ablation: none versus flips, crops, and color jitter.",
             "stretch": "Compare against a tiny pretrained backbone (a preview of transfer learning)."},
            {"title": "Imbalanced medical-style images",
             "data": "A small chest X-ray (pneumonia) set, binary.", "goal": "Classify under class imbalance.",
             "build": "A CNN with an imbalance strategy (class weighting or resampling).",
             "study": "Report precision, recall, and F1 (not just accuracy) and show the effect of the imbalance fix.",
             "stretch": "Add a class-activation (Grad-CAM-style) visualization."},
            {"title": "Traffic-sign recognition",
             "data": "GTSRB subset.", "goal": "Multiclass sign classifier.",
             "build": "A CNN classifier.",
             "study": "Compare input normalization schemes and input image sizes.",
             "stretch": "Test robustness to brightness and small rotations."},
            {"title": "CNN versus MLP",
             "data": "CIFAR-10 or FashionMNIST.", "goal": "Quantify the value of convolution.",
             "build": "A CNN and a parameter-matched MLP.",
             "study": "Compare accuracy and the generalization gap; explain the difference via inductive bias.",
             "stretch": "Visualize the first-layer filters of the CNN."},
            {"title": "Feature maps and receptive fields",
             "data": "Any image dataset.", "goal": "Interpret a trained CNN.",
             "build": "A CNN, plus code to extract and visualize feature maps across layers.",
             "study": "Relate receptive-field growth to what each layer appears to detect.",
             "stretch": "Add occlusion-sensitivity maps."},
            {"title": "Optimizer and learning-rate study",
             "data": "CIFAR-10.", "goal": "A rigorous optimization study.",
             "build": "A single fixed CNN architecture.",
             "study": "Grid over {SGD, SGD+momentum, Adam} and three learning rates; report curves and final accuracy.",
             "stretch": "Add a learning-rate schedule and measure the effect."},
            {"title": "Corruption robustness",
             "data": "FashionMNIST or CIFAR-10 with synthetic corruptions.", "goal": "Measure robustness.",
             "build": "A CNN classifier.",
             "study": "Accuracy under noise, blur, and brightness shifts; test augmentation as a defense.",
             "stretch": "Build a small CIFAR-10-C-style corruption benchmark."},
            {"title": "Depth and residual connections",
             "data": "CIFAR-10.", "goal": "See why residuals matter.",
             "build": "A plain deep CNN and a residual CNN.",
             "study": "Increase depth (for example 8, 14, 20 layers) and compare trainability with and without residuals.",
             "stretch": "Measure gradient norms by layer to explain the difference."},
        ],
    },
    "final": {
        "title": "Final project examples",
        "badge": "Final",
        "meta": "35% of the grade with a short oral defense · proposal around week 8 · due week 13",
        "intro": "The final project takes a task end to end with any architecture family from the course. "
                 "Work solo or in a pair: frame the task, build a suitable network, train and tune it, "
                 "diagnose failures, and report results. The examples below span vision, sequences, and "
                 "representation learning; propose your own variant if you prefer.",
        "deliverables": [
            "A one-page proposal (around week 8).",
            "Working code and a short report with results and curves.",
            "A half-page reflection on what the AI assistant did versus what you worked out yourself.",
            "A short oral defense of your design decisions.",
        ],
        "fields": [("data", "Data"), ("idea", "Idea"), ("methods", "Methods"), ("eval", "Evaluation"), ("stretch", "Stretch goal")],
        "examples": [
            {"title": "Transfer-learning regimes",
             "data": "A small image dataset.", "idea": "When does transfer learning help?",
             "methods": "Compare from-scratch, frozen-features, and fine-tuning a pretrained backbone under a fixed budget.",
             "eval": "Accuracy versus training cost across regimes; characterize when transfer wins.",
             "stretch": "Vary the target dataset size and find the crossover point."},
            {"title": "Sentiment classification with LSTM/GRU",
             "data": "A small text sentiment set (for example an IMDB or SST subset).", "idea": "Sequence classification.",
             "methods": "An embedding layer with an LSTM or GRU.",
             "eval": "Accuracy and F1; compare LSTM versus GRU and long versus short inputs.",
             "stretch": "Add pretrained word embeddings."},
            {"title": "Character-level language model",
             "data": "A plain-text corpus (for example a public-domain book).", "idea": "Generate text with a recurrent net.",
             "methods": "A character-level RNN or LSTM.",
             "eval": "Held-out perplexity plus qualitative samples; study the sampling temperature.",
             "stretch": "Compare an RNN with an LSTM at matched size."},
            {"title": "Image denoising autoencoder",
             "data": "MNIST or FashionMNIST with added noise.", "idea": "Denoise images and inspect the latent space.",
             "methods": "A convolutional autoencoder.",
             "eval": "Reconstruction error and latent-space structure (clusters, interpolation).",
             "stretch": "Use reconstruction error for anomaly detection."},
            {"title": "Contrastive representation learning",
             "data": "CIFAR-10 (labels withheld for pretraining).", "idea": "Learn features without labels.",
             "methods": "A SimCLR-style setup: augmentations, a contrastive loss, and a linear probe.",
             "eval": "Linear-probe accuracy versus a supervised baseline at low label counts.",
             "stretch": "Compare two augmentation policies and their effect on the representation."},
            {"title": "CNN + RNN encoder-decoder",
             "data": "A small image-to-sequence toy dataset.", "idea": "Combine vision and sequence models.",
             "methods": "A CNN encoder feeding an RNN decoder.",
             "eval": "A task-appropriate metric; ablate the encoder.",
             "stretch": "Add an attention-free pooling variant and compare."},
            {"title": "Time-series forecasting",
             "data": "A public time series (for example energy or weather).", "idea": "Forecast future values.",
             "methods": "An RNN or LSTM against a naive or linear baseline.",
             "eval": "MAE and RMSE; study how error grows with the forecast horizon.",
             "stretch": "Add exogenous features and measure the gain."},
            {"title": "Audio classification via spectrograms",
             "data": "A small audio set (for example an ESC-50 or UrbanSound subset).", "idea": "Treat spectrograms as images.",
             "methods": "A CNN, optionally a pretrained image backbone.",
             "eval": "Classification accuracy; try time and frequency augmentation.",
             "stretch": "Compare raw-waveform input against the spectrogram."},
            {"title": "An empirical optimization study",
             "data": "A task of your choice.", "idea": "A careful, controlled empirical study.",
             "methods": "A fixed architecture with a rigorous protocol over optimizers and regularizers.",
             "eval": "Curves with multiple seeds and visible variance, leading to clear conclusions.",
             "stretch": "Add confidence intervals via bootstrapping."},
            {"title": "An end-to-end applied problem",
             "data": "A Kaggle-style image or tabular problem.", "idea": "Solve a real problem end to end.",
             "methods": "An appropriate neural architecture with a sound train/validation/test protocol.",
             "eval": "A leaderboard-style metric reported honestly on a held-out split.",
             "stretch": "Compare against a strong non-neural baseline."},
        ],
    },
}

ORDER = ["midterm", "final"]
